### ISSUE TITLE
Update FAQ/messages: Add term "upside down" to "turn over" for clarification

### ISSUE THREAD

**Issue by dalb8** [udamken/mindbell#32]
It says to "turn over" in the FAQ. It seems to me that this isn't very good English.

**Comment by udamken** [comment]
What is your suggestion?

**Comment by dalb8** [comment]
I think you mean to say turn off. This could also be changed within the app.

**Comment by udamken** [comment]
After the stylized bell (or bowl) has been "turned over" its shown upside down, so "turn off" is not what is meant.

**Comment by dalb8** [comment]
I don't see any upside down bowl; where is it shown?

**Comment by dalb8** [comment]
aha I see an upturned bell when I expand the notification or mute it otherwise.

**Comment by dalb8** [comment]
Perhaps it should be referred to as the status bar or notofication icon. I had that mostly disabled so it was less obvious.

**Comment by udamken** [comment]
Update FAQ and MindBell messages for clarification.

**Comment by udamken** [comment]
Update to message to be release with version 3.2.

**Comment by dalb8** [comment]
There are still a few instances of turn over on the site.

**Comment by udamken** [comment]
From a another discussion I've learned that "turning over is about the movement itself" whereas "upsided down is about the exact position". So I came to the conclusion that there is no need to get rid of the verb "turn over" but to get rid of the state "turned over". The new title of this issue should reflect this conclusion. However, I've enriched the FAQ by some more screenshots and explanations.
