### ISSUE TITLE
Earphones volume

### ISSUE THREAD

**Issue by dalb8** [udamken/mindbell#34]
To revive the issue #5. If the volume of the audio in the speaker is set lower than default then the earphone volume may be a bit low to be heard. 

There are projects like https://github.com/jpeddicord/speedofsound and https://github.com/brightify/autoamplifier that do clever things with adjusting sound to ambient levels.

I wonder would a solution involve a setting that sets the volume to a percentage of the media volume. This is the way https://github.com/yuttadhammo/BodhiTimer does it. 

BTW, there are surprisingly few FOSS meditation timers out there and the former served me well for ages but it's not getting maintained. If you are thinking of customising the meditation timer then I will be glad to test them out .

**Comment by udamken** [comment]
Regarding testing: Please register as beta user to test new versions and leave non-public feedbacks. Thanks.

**Comment by udamken** [comment]
Choosing an audio stream and using volume control of this audio stream - introduced with issue #19 - should be enough handling for earphone IMHO.
