### ISSUE TITLE
Downloading apk from Github

### ISSUE THREAD

**Issue by dalb8** [udamken/mindbell#37]
If browsing Github mobile website for the APK it says that the file is too big to show. Perhaps you should show users to the desktop version of the page or post the APKs at the releases section of github. This would also reduce the size of the git repo somewhat

**Comment by master-bob** [comment]
I think this is no longer an issue and can be closed.

I can download the APK without any issues on mobile (Chrome 83.0.4103.106 on Android 8) when going to https://github.com/udamken/mindbell/releases.

**Comment by udamken** [comment]
However, even if it still existed, I'm not going to solve GitHub issues. Thanks for checking.
