### ISSUE TITLE
Implement quick settings tile

### ISSUE THREAD

**Issue by dalb8** [udamken/mindbell#39]
On Android 7 apps can make quick settings tiles à là WiFi or Bluetooth. One tap could mute indefinitely, for an hour or until the following day. A long tap could probably open the main activity.

I'm not sure if it can be placed when the app is installed or if it's up to the user to add it himself.

**Comment by udamken** [comment]
This might replace the notification action "mute for..." when more users are on Android 7

**Comment by udamken** [comment]
I don't think it is very helpful to implement more ways for suppressing the reminder bell. As of 3.2.6 you can choose the audio stream and make full use of do-not-disturb modes.
