### ISSUE TITLE
Meditation bell not sounding

### ISSUE THREAD

**Issue by dalb8** [udamken/mindbell#40]
I'm not sure under what exact circumstances this occurs. For example, I set duration 70mins , 4 periods and x, 8, 1, x. Earlier, I was experimenting with durations and got the bell to sound but cannot now reproduce. The app is running on stock LG G4 running android 6

**Comment by dalb8** [comment]
it seems to be caused by pause audio on sound being enabled

**Comment by udamken** [comment]
Please send me an e-mail from the help dialog. It contains log entries to help me analyzing. Before that please follow this checklist: http://dknapps.de/mindbell-notringing/ ... most probably it's a battery optimization problem which is device and vendor dependent.

**Comment by dalb8** [comment]
Seems like the audio pauses anyway even though the setting is disabled.

**Comment by udamken** [comment]
Add the following to the FAQ entry mentioned above:

Is ‘Pause audio on sound’ enabled in the settings of MindBell? Please disable that option. It doesn’t work properly on devices of some vendors, e.g. Samsung or LG.
