### ISSUE TITLE
Vibration strength

### ISSUE THREAD

**Issue by dalb8** [udamken/mindbell#48]
In my opinion, the weakest vibration strength is too weak while the others are too strong. 

The rhythms are fine, it's just the strength that's a problem. I have a setting to set vibration strength on my phone and the app doesn't obey it.

Also I don't understand what b and r refer to: pattern or strength?

**Comment by udamken** [comment]
Vibration is produced by [Vibrator](https://developer.android.com/reference/android/os/Vibrator.html). IMHO there is no strength parameter, a pattern array only let's you specify lengths of vibration and quiesce periods. Maybe setting the strength is a device dependend special ... please send me an e-mail with more information about this.
The b's and r's in the settings are not technical at all. They are some sort of a phonetic spelling.

**Comment by udamken** [comment]
Only a very small set of devices seem to offer control of the strength of vibration. After discussing this it seems that if an app uses only notifications for vibration, then the strength setting is respected, though it is not respected if using the Vibrator API. Therefore this sounds to be an Android bug to me.

Following the answeres to http://stackoverflow.com/q/2888043 a lower intensity could be simulated by injecting small phases of silence into the vibration pattern.

But I have no idea whether this could be implemented reliably and predictably for all devices. Neither am I able to test this on a variety of devices. Therefore I'm not going to implement anything beyond the standard pattern vibration.
