### ISSUE TITLE
Hide status on lockscreen

### ISSUE THREAD

**Issue by dalb8** [udamken/mindbell#49]
I think this setting doesn't work. Whether it's enabled or not  I have a status notification with text on the lockscreen.

**Comment by udamken** [comment]
The option is about the status *text* on the lock screen and works well for me. Please send me an e-mail with device information, log entries and your settings (can be achieved from the help dialog; if using logcat opening and closing the settings logs all settings).

For the time being I'll close this issue and will reopen it if there's a problem in the logs.

**Comment by dalb8** [comment]
I definitely get the same text no matter what setting.

Unfortunately, I can't send a log because I'm away from my computer and my phone truncates the log.

**Comment by udamken** [comment]
To see the difference go to the Android Settings, set Notifications > Settings > On the lock screen > Hide sensitive notification content.

**Comment by dalb8** [comment]
I dont get it: it says unlock to see the sensitive info no matter what the setting in mindbell is.

**Comment by udamken** [comment]
... ah, the content is always suppressed?

... you can even specify for each application whether and how to show notifications: For me the generic and specific setting are identical (Hide ...) and the MindBell setting makes a difference. If the generic is Show completely (or whatever it's called) and the specific is Hide... then the MindBell setting is ignored ...

Looks like an Android bug to me ...

Ciao, Uwe

Am 23. April 2017 19:27:23 MESZ schrieb dalb8 <notifications@github.com>:
>I dont get it: it says unlock to see the sensitive info no matter what
>the setting in mindbell is.
>
>Le 23 avril 2017 18:11:29 GMT+01:00, Uwe Damken

**Comment by dalb8** [comment]
I have both generic and specific to hide and Mindbell makes no difference.

**Comment by udamken** [comment]
To clarify my comment before:

You can even specify for each application whether and how to show notifications. Under Notification > Settings use the gear for the generic setting for all apps or specificely per app via "On the lock screen".

For me (Android 7.0) the generic and specific setting are identical ("Hide sensitive notification content") and the MindBell setting makes a difference. If the generic is "Show all notification content" and the specific is "Hide sensitive notification content" then the MindBell setting is ignored.

The MindBell setting only sets the visibility of the notification to "public" or "private". Whether the text is displayed on the lock screen is decided by Android itself depending on the three mentioned pieces of information.
