### ISSUE TITLE
Update FAQ on nomenclature

### ISSUE THREAD

**Issue by dalb8** [udamken/mindbell#52]
Yes, the bell looks like a bowl, however in my experience in Zen people call them bells, or in French, cloches. This article is informative: as it points out: Tibetan singing bowls are a type of bell: https://en.m.wikipedia.org/wiki/Singing_bowl. 

As the article points out, another accurate term is bowl gong, the technical term for a gong that sits on a cushion. I.e. bell or gong are more appropriate than bowl as the latter isn't a 'musical' instrument.

Just don't call it a horn :-) http://www.mindhorn.co.uk/tour.

**Comment by dalb8** [comment]
OK they call them gongs too: http://www.boutiquezen.com/boutique/accessoires.asp?IdCategorie=14

**Comment by udamken** [comment]
Great :-) ... added a link to the article to my FAQ.
