### ISSUE TITLE
Wish to have a choice of several singing bowl sounds

### ISSUE THREAD

**Issue by udamken** [udamken/mindbell#53]

**Comment by dalb8** [comment]
In Buddhist temples a small bell often signals meditation. However, the volume can be changed on a smartphone, so larger bells, which tend to be used during ceremonies, could be offered too.

Here is an example of a medium-sized one: http://freesound.org/people/Juular/sounds/367128/.

They are called keisu in Japan: http://global.sotozen-net.or.jp/eng/library/glossary/individual.html?key=bowl_bell. As the article says, the bells are made of copper [by hand-hammering]. Tibetan singing bowls are probably made of bell metal: https://en.m.wikipedia.org/wiki/Bell_metal. Cheap ones might be machined from brass.

I've seen Tibetans use a large one to begin and a smaller one to end.

**Comment by dalb8** [comment]
I'm actually at a traditional Zen temple now and they use a hanging bell for signalling meditation, in two different sizes. A standing bell is used for ceremonies.

**Comment by udamken** [comment]
Release 3.2.5 requests READ_EXTERNAL_STORAGE permission when you want to choose a ringtone. After putting any sound into 'Notifications' directory on your device you can choose it as sound for MindBell. But it's length may not exceed 10 seconds.
