### ISSUE TITLE
Visual bell transition

### ISSUE THREAD

**Issue by dalb8** [udamken/mindbell#55]
It can feel slightly abrupt to have the bell appear; especially in battery saver mode when animations are turned off.

 How about having the notification appear one second before as a warning? This wouldn't work in immersive mode: how about muting MindBell altogether if an app is in immersive mode? If this isn't feasible, perhaps the bell could be animated such as with a fade-in.

**Comment by udamken** [comment]
From 3.2.5 on this can be reached by adding an own sound with silence in the beginning or with the workaraound setting that uses sounds with 3 s of silence before the bell. If reminder notification or vibration are active they come "before" you can hear the bell itself.
