### ISSUE TITLE
sometime playing Mindfulness bell sound just 0.1~1 second on LG android 6.0

### ISSUE THREAD

**Issue by cjnama** [udamken/mindbell#70]
I used default setting no change any thing.
but sometime playing Mindfulness bell sound just 0.1~1 second on LG-X230K android 6.0

sometime is ok.

I can not find  root cause of the issue

So I dowload the other app for test. it run very good every times. 

app name: Zazen Meditation Timer
[https://play.google.com/store/apps/details?id=de.gaffga.android.zazentimer](url)

It no any same  issue like mindbell so I can say this is not my cell phone issue.

Could you find  root cause of the issue?

Thank you.

PS
Could you add Meditation log function (shows total  Meditation time or   Meditation times)?

**Comment by udamken** [comment]
Please send an email to mindbell@dknapps de. This is for tracking changes not for tracking user questions.

What do you mean by "bell sound just 0.1~1 second"? Sound ist cut off after under a second? Reminder bell or during meditation? Sounds like you have pause audio on sound enabled in the mute rules section of the MindBell settings. Please disable that, it might not work correctly on LG phones. If the problem persists please send me an email from within MindBell (help dialog or problem solving section).

>> It no any same issue like mindbell so I can say this is not my cell phone issue. << This is not necessarily true because different apps may use different mechanisms ...

**Comment by udamken** [comment]
>> Could you add Meditation log function (shows total Meditation time or Meditation times)? <<

No, I won't. IMHO is meditation is nothing to compete and measure performance

**Comment by cjnama** [comment]
>>What do you mean by "bell sound just 0.1~1 second"? 

Sound ist cut off after under a second (or 0.1~ 1 sec) , it is not  complete .

>> Reminder bell or during meditation? 
Reminder bell  ( btw I don't like Reminder bell playing  during meditation but no any  setting can mute it )

>> you have pause audio on sound enabled in the mute rules section ?
no , I had not check (enabled) it

**Comment by udamken** [comment]
As said in my first comment: If the problem persists please send me an email from within MindBell (help dialog or problem solving section).

**Comment by udamken** [comment]
BTW: Reminder bell is not played during meditation. Maybe you mean the intermediate bells but there are no intermediate bells if you choose only one interval.

**Comment by cjnama** [comment]
sorry I find help dialog or problem solving section now but not found yet
>>Maybe you mean the intermediate bells ?

the bell setting section name is "Active times and rhythm"
I call it " Mindfulness bell" due to it playing every 15 min in Plum Village ( French: Village des pruniers)

**Comment by udamken** [comment]
My last comment was in response to >>btw I don't like Reminder bell playing during meditation but no any setting can mute it<<.

>>sorry I find help dialog or problem solving section now but not found yet<< ... if you found the problem solving section then there is an option to send an e-mail ... or there is a button for this in the help dialog ... depends on the version you are using.
