### ISSUE TITLE
Bell rings again if user navigates to the app after the bell has rung

### ISSUE THREAD

**Issue by jpassaro** [udamken/mindbell#73]
Setup:
* Bell rings
* User navigates away (e.g. home button, cancel button)
* User reopens Mindbell by going through list of open apps

Expected:
* Regular app view opens up, including on/off toggle & options etc., and bell does not ring

Actual:
* The screen from the reminder is displayed, with no controls or navigation of any kind, and the bell rings again!

Is it possible to have this screen
1) not ring again if it is opened by the user (as opposed to opened from a timed event), and
2) offer some clear way to access the app's regular menus / dialogs? (Either by adding them to this view or giving it e.g. a "Dismiss" button that brings you to the main app view)

Happy to contribute a patch if somebody can point me at the right section of code.

**Comment by udamken** [comment]
Already solved with #69
